utils::globalVariables(
  c(
    "MonthSimulated",
    "HeiOpenGrowMonth1",
    "GeneralCategories",
    "Others",
    "MonthLac",
    "Garbage",
    "Categories",
    "Month",
    "day_max",
    "day_min",
    "mean_body_weight",
    "mean_body_weight_kg",
    "mean_cow_weight_kg",
    "bw_change_total_kg",
    "Phase",
    "bw_change_acum_kg",
    "cow_bw_parturium_kg",
    "final_body_weight_kg",
    "final_body_weight",

    "milk_yield_kg_2",
    "milk_yield_kg_fpc",
    "dry_matter_intake_kg_animal",
    "forage_intake_kg",
    "milk_solids_intake_kg",
    "milk_yield_kg_cow2",
    "starter_intake_kg",
    "enteric_methane_g_animal_day",
    "gei_mj_day",

    "digestible_volatile_solids_kg_d",
    "dm_manure_output_kg_day",
    "fecal_nitrogen_excreted_d",
    "fresh_manure_output_kg_day",
    "milk_n_output_g",
    "total_nitrogen_excreted_g",
    "total_nitrogen_ingested_g",
    "volatile_solids_kg_d",
    "milk_protein",
    "total_phosphorus_excretion_g",
    "total_phosphorus_excretion_milk",
    "total_phosphorus_ingested_g",
    "total_potassium_excretion_milk",
    "total_potassium_ingested_g",

    # nh3 barn emissions module
    "Const",
    "M",
    "Q",
    "aver_tempC",
    "county",
    "gama_densi",
    "loss_animal_kg",
    "loss_kg_m2",
    "r",
    "tan_kg_m2",
    "wi_weather",
    "yday",

    "NumberAnimals",
    "area",
    "k_removal",
    "lime_applied",
    "n_removal",
    "p_removal",
    "total_manure",
    "total_n_applied",
    "total_solids_kg",
    "total_volatile_solids_kg",
    "ts_manure urea_pct_applied",
    "vs_manure yield",
    "ts_manure",
    "urea_pct_applied",
    "vs_manure",
    "yield",

    "n2o_emissions_g",
    "nitrogen_fix",
    "taglist",
    "total_animals",
    "total_ch4_kg",
    "total_n_fixed",
    "total_n_removal",
    "total_storage_kg",
    "y",
    "name",



    "milk_intake",
    "age",
    "dmi"
  )
)
