utils::globalVariables(
  c(
    "MonthSimulated",
    "HeiOpenGrowMonth1",
    "GeneralCategories",
    "Others",
    "MonthLac",
    "Garbage",
    "Categories",
    "Month",
    "day_max",
    "day_min",
    "mean_body_weight",
    "mean_body_weight_kg",
    "mean_cow_weight_kg",
    "bw_change_total_kg",
    "Phase",
    "bw_change_acum_kg",
    "cow_bw_parturium_kg",
    "final_body_weight_kg",
    "final_body_weight",

    "milk_yield_kg_2",
    "milk_yield_kg_fpc",
    "dry_matter_intake_kg_animal",
    "forage_intake_kg",
    "milk_solids_intake_kg",
    "milk_yield_kg_cow2",
    "starter_intake_kg",
    "enteric_methane_g_animal_day",
    "gei_mj_day",

    "digestible_volatile_solids_kg_d",
    "dm_manure_output_kg_day",
    "fecal_nitrogen_excreted_d",
    "fresh_manure_output_kg_day",
    "milk_n_output_g",
    "total_nitrogen_excreted_g",
    "total_nitrogen_ingested_g",
    "volatile_solids_kg_d",
    "milk_protein",
    "total_phosphorus_excretion_g",
    "total_phosphorus_excretion_milk",
    "total_phosphorus_ingested_g",
    "total_potassium_excretion_milk",
    "total_potassium_ingested_g",

    # nh3 barn emissions module
    "Const",
    "M",
    "Q",
    "aver_tempC",
    "county",
    "gama_densi",
    "loss_animal_kg",
    "loss_kg_m2",
    "r",
    "tan_kg_m2",
    "yday",
    "wisconsin_weather_data",
    "area_exposed_m2",
    "const",
    "gamma_densi",
    "manure_solution_mass",
    "manure_solution_pH",
    "temp_c",
    "total_tan_excreted_g",
    "total_tan_kg",
    "total_urine_excretion_kg",
    "total_urine_kg",
    "urine_nitrogen_excreted_g",

    "NumberAnimals",
    "area",
    "k_removal",
    "lime_applied",
    "n_removal",
    "p_removal",
    "total_manure",
    "total_n_applied",
    "total_solids_kg",
    "total_volatile_solids_kg",
    "ts_manure urea_pct_applied",
    "vs_manure yield",
    "ts_manure",
    "urea_pct_applied",
    "vs_manure",
    "yield",
    "totalN",
    "totalTAN",

    "n2o_emissions_g",
    "nitrogen_fix",
    "taglist",
    "total_animals",
    "total_ch4_kg",
    "total_n_fixed",
    "total_n_removal",
    "total_storage_kg",
    "y",
    "name",
    "total_potassium_excretion_g",

    "Source",
    "Herd",
    "Barn",
    "Manure",
    "Crop production and purchased feeds",
    "Fuel",




    "milk_intake",
    "age",
    "dmi",
    "Calves",

    # Manure
    "co2_lime",
    "co2_urea",
    "nh3_n_fertilizer",
    "nitrous_oxide",
    "storage_ch4_emissions_kg",
    "year_day",

    "Methane",
    "fecal_n_kg n_mineralized_feces",
    "remaining_tan_kg",
    "total_fecal_n_escreted_g",
    "total_methane total_milk_kg",
    "total_storage_N_loss",
    "fecal_n_kg",
    "n_mineralized_feces",
    "total_methane",
    "total_milk_kg",
    "CO2eq",
    "Qntdds",
    "carbon_foot",
    "head",
    "total",
    "dmi_kg",
    "total_nitrogen_field",
    "total_tan_field",
    "water_intake_l_animal",
    "total_co2_eq_fuel",
    "total_n_fert"


  )
)
